"""descreva a alteração

Revision ID: 10c03e7439fd
Revises: 0001_initial_movie_schema
Create Date: 2026-09-27 17:25:44.817592

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '10c03e7439fd'
down_revision: Union[str, Sequence[str], None] = '0001_initial_movie_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
