"""add catalog sorting indexes

Revision ID: dccf1d8c36b3
Revises: 10c03e7439fd
Create Date: 2026-09-27 18:31:50.342902

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'dccf1d8c36b3'
down_revision: Union[str, Sequence[str], None] = '10c03e7439fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fact_movies_performance', schema=None) as batch_op:
        batch_op.create_index('ix_fact_movies_performance_popularidade', ['popularidade', 'sk_movie_id'], unique=False)

    with op.batch_alter_table('movie_reviews', schema=None) as batch_op:
        batch_op.create_index('ix_movie_reviews_sk_movie_id_nota', ['sk_movie_id', 'nota'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_movie_reviews_sk_movie_id_nota')

    with op.batch_alter_table('fact_movies_performance', schema=None) as batch_op:
        batch_op.drop_index('ix_fact_movies_performance_popularidade')

    # ### end Alembic commands ###
